update on installation process on termux
omarmohamedkh/Timewarrior-Pomodoro pull request #8
Opened 2022-09-27 14:40 UTC by sakarimov

the installation process on termux should be updated, as written in it's documentation https://github.com/termux/termux-packages/wiki/Termux-file-system-layout, the ```$PREFIX``` will immediately refer to ```/data/data/com.termux/files/usr```

2022-09-28 11:58 UTC, omarmohamedkh requested changes

2022-09-28 11:58 UTC, omar-khallaf commented on README.md
> +# Use -DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX/usr for termux on android
You're right, but shouldn't it be `-DCMAKE_INSTALL_PREFIX=$PREFIX`?
`$TERMUX_PREFIX` isn't defined in my environment.

2022-09-28 21:18 UTC, sakarimov commented on README.md
> +# Use -DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX/usr for termux on android
as written in the documentation, ```$TERMUX_PREFIX = /data/data/com.termux/files```, and ```$PREFIX = /data/data/com.termux/files/usr```, i'm not very familiar with termux actually, i don't know how is the most common variable used, therefore i only add ```$TERMUX_PREFIX```, or should it be written like this?

```# Use -DCMAKE_INSTALL_PREFIX=$PREFIX or $TERMUX_PREFIX/usr for termux on android```

2022-09-28 23:37 UTC, omarmohamedkh commented on README.md
> +# Use -DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX/usr for termux on android
I didn't read well.
`$TERMUX_PREFIX` seems to be defined in the context of packaging, so for this manual install I think
`-DCMAKE_INSTALL_PREFIX=$PREFIX` is the right choice.

2022-09-29 00:16 UTC, sakarimov commented on README.md
> +# Use -DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX/usr for termux on android
i see, good choice

2022-09-29 00:17 UTC, closed without merging

2022-09-29 02:22 UTC, omarmohamedkh commented on README.md
> +# Use -DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX/usr for termux on android
Wait you mentioned something important it should be just `$PREFIX` not `$PREFIX/usr` if you don't mind you can update it or I will do it later.
Thanks again.